### ISSUE TITLE
'Modiying' a default instance using 'with'

### ISSUE THREAD

**Issue by richardpawson** [elan-language/Elan#132]
See Ignored test on T45

Currently, if you write e.g.

`var a = default Foo with {name = "bar"}`

`a `is an instance of DefaultFoo with the name set, but, of course, all the methods are empty. We need to change this so that either:

- In the expression above `a` is a proper Foo.  OR
- It is not possible to apply `with `to a default.

**Comment by scascarini** [comment]
After discussion the actual behaviour is that 'with' on a default just returns a new unmodified default instance. Conveniently this is how it already works. Test updated.
