### ISSUE TITLE
Function methods

### ISSUE THREAD

**Issue by richardpawson** [elan-language/Elan#52]
**Moved to CleanUp Milestone to deal with new test**

Can access but not mutate any properties

Cannot call any procedure method

**Comment by richardpawson** [comment]
Reopened and assigned as new test added - currently Ignored as not implemented.

**Comment by richardpawson** [comment]
Closed again as new test removed - because I forgot that we haven't yet implemented expression functions (that's in the next milestone!)

**Comment by scascarini** [comment]
Add new test for problem with function name hiding
